<?php
$labels['label_title'] = 'Етикети';
$labels['label_create'] = 'Нов етикет';
$labels['label_set'] = 'Избиране на етикет';
$labels['label_matches'] = 'включва';
$labels['label_color'] = 'цвят';
$labels['label_delete'] = 'изтриване';
$labels['label_name'] = 'име';
$labels['label_folder'] = 'в папките ';
$labels['label_all'] = 'Всички папки';
$labels['label_pref'] = 'Настройки на етикетите';

$labels['deleteconfirm'] = 'Сигурни ли сте, че желаете да изтриете този етикет?';
$labels['add_row'] = 'добави';
$labels['delete_row'] = 'изтрий';

$labels['headererror'] = 'Грешка в условието на етикета';
$labels['inputempty'] = 'Моля попълнете условие';
$labels['invalidcolor'] = 'Избране е невалиден цвят';

$labels['check_highlighting'] = 'Проверете начинът на отбелязване';
$labels['highlighting'] = 'Начин на отбелязване';

$labels['check_labels'] = 'Проверяване на етикетите';
$labels['labels'] = 'Тип на етикетите';

$labels['check_error'] = 'Грешка при проверяване на етикетите';

$labels['label_mode'] = 'Начин на показване';
$labels['search_info'] = 'Информация за търсене';

$labels['display_label_on'] = 'Показването на етикети е включено';
$labels['display_label_off'] = 'Показването на етикети е изключено ';
?>