<?php
$labels['label_title'] = 'Štítky';
$labels['label_create'] = 'Vytvoř štítek';
$labels['label_set'] = 'Přiřaď štítek';
$labels['label_matches'] = 'obsahuje';
$labels['label_color'] = 'barva';
$labels['label_delete'] = 'Smazat';
$labels['label_name'] = 'název';
$labels['label_folder'] = 'hledat v ';
$labels['label_all'] = 'Všechny složky';
$labels['label_pref'] = 'Správa štítků';

$labels['deleteconfirm'] = 'Opravdu chcete smazat tento štítek?';
$labels['add_row'] = 'Přidat';
$labels['delete_row'] = 'Smazat';

$labels['headererror'] = 'Chyba v pravidle zprávy';
$labels['inputempty'] = 'Jedna nebo více položek nevyplněna(o)';
$labels['invalidcolor'] = 'Neplatná barva';

$labels['check_highlighting'] = 'Kontrola režimu zvýraznění';
$labels['highlighting'] = 'Režim zvýraznění';

$labels['check_labels'] = 'Kontrola režimu štítků';
$labels['labels'] = 'Režim štítků';

$labels['check_error'] = 'Chyba kontroly režimu';

$labels['label_mode'] = 'Režim zobrazení';
$labels['search_info'] = 'Vyhledávání informací';

$labels['display_label_on'] = 'Zobrazení seznamu štítku zapnuto';
$labels['display_label_off'] = 'Zobrazení seznamu štítku vypnuto';
?>
