<?php
$labels['label_title'] = 'Labels';
$labels['label_create'] = 'Label erstellen';
$labels['label_set'] = 'Label setzen';
$labels['label_matches'] = 'enthält';
$labels['label_color'] = 'Farbe';
$labels['label_delete'] = 'löschen';
$labels['label_name'] = 'Name';
$labels['label_folder'] = 'suchen in ';
$labels['label_all'] = 'Allen Ordnern';
$labels['label_pref'] = 'Labels verwalten';

$labels['deleteconfirm'] = 'Wollen Sie diesen Label löschen?';
$labels['add_row'] = 'hinzufügen';
$labels['delete_row'] = 'löschen';

$labels['headererror'] = 'Fehler in der Nachrichtenregel';
$labels['inputempty'] = 'Einige ihrer Regeln sind leer';
$labels['invalidcolor'] = 'Ungültige Farbe';

$labels['check_highlighting'] = 'Checking highlighting mode';
$labels['highlighting'] = 'Highlighting mode';

$labels['check_labels'] = 'Checking labels mode';
$labels['labels'] = 'Labels mode';

$labels['check_error'] = 'Error checking mode';

$labels['label_mode'] = 'Mode display';
$labels['search_info'] = 'Search information';

$labels['display_label_on'] = 'Labelliste wird angezeigt';
$labels['display_label_off'] = 'Labelliste wird nicht angezeigt';

?>