<?php
$labels['label_title'] = 'Labels';
$labels['label_create'] = 'Create label';
$labels['label_matches'] = 'matches';
$labels['label_color'] = 'color';
$labels['label_delete'] = 'delete';
$labels['label_name'] = 'name';
$labels['label_folder'] = 'search in ';
$labels['label_all'] = 'All folder';
$labels['label_pref'] = 'Management of labels';

$labels['deleteconfirm'] = 'Do you really want to delete this label?';
$labels['add_row'] = 'add';
$labels['delete_row'] = 'delete';

$labels['headererror'] = 'Error in message rule';
$labels['inputempty'] = 'One or more of your matches are empty';
$labels['invalidcolor'] = 'Invalid color';

$labels['check_highlighting'] = 'Checking highlighting mode';
$labels['highlighting'] = 'Highlighting mode';

$labels['check_labels'] = 'Checking labels mode';
$labels['labels'] = 'Labels mode';

$labels['check_error'] = 'Error checking mode';

$labels['label_mode'] = 'Mode display';


?>