<?php
/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Message Labels plugin              |
 | Copyright (C) 2013, JPL TSolucio, S.L. (Joe Bordes)                   |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version.                                                    |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/
$labels['label_title'] = 'Etiquetas';
$labels['label_create'] = 'Crear etiqueta';
$labels['label_set'] = 'Etiquetar';
$labels['label_matches'] = 'coincide';
$labels['label_color'] = 'color';
$labels['label_delete'] = 'eliminar';
$labels['label_name'] = 'nombre';
$labels['label_folder'] = 'buscar en ';
$labels['label_all'] = 'Todas las carpetas';
$labels['label_pref'] = 'Administración de etiquetas';

$labels['deleteconfirm'] = '¿Realmente quieres eliminar esta etiqueta?';
$labels['add_row'] = 'añadir';
$labels['delete_row'] = 'eliminar';

$labels['headererror'] = 'Error en regla de mensaje';
$labels['inputempty'] = 'Uno o más de las coincidencias está vacía';
$labels['invalidcolor'] = 'Color inválido';

$labels['check_highlighting'] = 'Comprobando modo de marcar';
$labels['highlighting'] = 'Modo de Marcar';

$labels['check_labels'] = 'Comprobando modo de etiquetas';
$labels['labels'] = 'Modo de Etiquetas';

$labels['check_error'] = 'Error comprobando el modo';

$labels['label_mode'] = 'Modo visualización';
$labels['search_info'] = 'Información Búsqueda';

$labels['display_label_on'] = 'Mostrar lista etiquetas activado';
$labels['display_label_off'] = 'Mostrar lista etiquetas desactivado';

?>
