<?php
$labels['label_title'] = 'Libellés';
$labels['label_create'] = 'Créer un libellé';
$labels['label_set'] = 'Set label';
$labels['label_matches'] = 'contient';
$labels['label_color'] = 'couleur';
$labels['label_delete'] = 'effacer';
$labels['label_name'] = 'nom';
$labels['label_folder'] = 'chercher dans ';
$labels['label_all'] = 'Tous les dossiers';
$labels['label_pref'] = 'Gestion des libellés';

$labels['deleteconfirm'] = 'Voulez vous vraiment effacer ce libellé?';
$labels['add_row'] = 'ajouter';
$labels['delete_row'] = 'effacer';

$labels['headererror'] = 'Erreur dans la régle de message';
$labels['inputempty'] = 'Une ou plusieurs de vos règles sont vides';
$labels['invalidcolor'] = 'Coleur non valide';

$labels['check_highlighting'] = 'Checking highlighting mode';
$labels['highlighting'] = 'Highlighting mode';

$labels['check_labels'] = 'Checking labels mode';
$labels['labels'] = 'Labels mode';

$labels['check_error'] = 'Error checking mode';

$labels['label_mode'] = 'Mode display';
$labels['search_info'] = 'Search information';

$labels['display_label_on'] = 'Afficher les libellés';
$labels['display_label_off'] = 'Masquer les libellés';

?>