<?php
$labels['label_title'] = 'Étiquettes';
$labels['label_create'] = 'Créer une étiquette';
$labels['label_set'] = 'Définir';
$labels['label_matches'] = 'correspondant à';
$labels['label_color'] = 'couleur';
$labels['label_delete'] = 'supprimer';
$labels['label_name'] = 'nom de l\'étiquette';
$labels['label_folder'] = 'chercher dans ';
$labels['label_all'] = 'Tous les dossiers';
$labels['label_pref'] = 'Préférences des Étiquettes';

$labels['deleteconfirm'] = 'Voulez-vous vraiment supprimer cette étiquette?';
$labels['add_row'] = 'ajouter une ligne';
$labels['delete_row'] = 'supprimer la ligne';

$labels['headererror'] = 'Erreur dans la configuration des règles des étiquettes';
$labels['inputempty'] = 'Un ou plusieurs de vos critères sont vides';
$labels['invalidcolor'] = 'Couleur invalide';

$labels['check_highlighting'] = 'Vérifier le mode surlignage';
$labels['highlighting'] = 'Mode surlignage';

$labels['check_labels'] = 'Vérifier mode affichage des étiquettes';
$labels['labels'] = 'Étiquettes';

$labels['check_error'] = 'Erreur de vérification du mode';

$labels['label_mode'] = 'Mode affichage';
$labels['search_info'] = 'Chercher une information';

$labels['display_label_on'] = 'Affichage de la liste des étiquettes activé';
$labels['display_label_off'] = 'Affichage de la liste des étiquettes désactivé';

?>
