<?php
$labels['label_title'] = 'Labels';
$labels['label_create'] = 'Maak label';
$labels['label_set'] = 'Plaats label';
$labels['label_matches'] = 'bevat';
$labels['label_color'] = 'kleur';
$labels['label_delete'] = 'verwijder';
$labels['label_name'] = 'naam';
$labels['label_folder'] = 'zoeken in ';
$labels['label_all'] = 'Alle mappen';
$labels['label_pref'] = 'Beheer labels';

$labels['deleteconfirm'] = 'Wil je dit label echt verwijderen?';
$labels['add_row'] = 'toevoegen';
$labels['delete_row'] = 'verwijderen';

$labels['headererror'] = 'Fout in berichtregel';
$labels['inputempty'] = 'Een of meer van uw overeenkomsten zijn leeg';
$labels['invalidcolor'] = 'Foutieve kleur';

$labels['check_highlighting'] = 'Controleren van benadrukken modus';
$labels['highlighting'] = 'Benadrukken modus';

$labels['check_labels'] = 'Controleren van labels modus';
$labels['labels'] = 'Labels modus';

$labels['check_error'] = 'Controleren op fouten modus';

$labels['label_mode'] = 'Toon modus';
$labels['search_info'] = 'Zoek informatie';

$labels['display_label_on'] = 'Lijst met labels is zichtbaar';
$labels['display_label_off'] = 'Lijst met labels is verborgen';

?>