<?php
$labels['label_title'] = 'Ярлыки';
$labels['label_set'] = 'Установить ярлык';
$labels['label_create'] = 'Создать ярлык';
$labels['label_matches'] = 'содержит';
$labels['label_color'] = 'цвет';
$labels['label_delete'] = 'удалить';
$labels['label_name'] = 'название';
$labels['label_folder'] = 'искать в ';
$labels['label_all'] = 'Все папки';
$labels['label_pref'] = 'Управление ярлыками';

$labels['deleteconfirm'] = 'Вы действительно хотите удалить этот ярлык?';
$labels['add_row'] = 'добавить';
$labels['delete_row'] = 'удалить';

$labels['headererror'] = 'Ошибка в правиле';
$labels['inputempty'] = 'Одно или более совпадений пусты';
$labels['invalidcolor'] = 'Неверный цвет';

$labels['check_highlighting'] = 'Выбран режим подсветки';
$labels['highlighting'] = 'Режим подсветки';

$labels['check_labels'] = 'Выбран режим ярлыков';
$labels['labels'] = 'Режим ярлыков';

$labels['check_error'] = 'Ошибка выбора режима';

$labels['label_mode'] = 'Выбор режима отображения';
$labels['search_info'] = 'Найти информацию';

$labels['display_label_on'] = 'Отображение списка ярлыков включено';
$labels['display_label_off'] = 'Отображение списка ярлыков отключено';


?>