<?php
$labels['label_title'] = '邮件标签';
$labels['label_create'] = '建立标签';
$labels['label_set'] = '安置标签';
$labels['label_matches'] = '匹配';
$labels['label_color'] = '颜色';
$labels['label_delete'] = '删除';
$labels['label_name'] = '标签名称';
$labels['label_folder'] = '搜寻。。';
$labels['label_all'] = '全部信箱';
$labels['label_pref'] = '标签管理';

$labels['deleteconfirm'] = '你是否要删除此标签？';
$labels['add_row'] = '增加';
$labels['delete_row'] = '删除';

$labels['headererror'] = '信息规矩有错误';
$labels['inputempty'] = '匹配不可空白';
$labels['invalidcolor'] = '颜色不正确';

$labels['check_highlighting'] = '提示检查模式';
$labels['highlighting'] = '提示模式';

$labels['check_labels'] = '标签检查模式';
$labels['labels'] = '标签模式';

$labels['check_error'] = '检查错误模式';

$labels['label_mode'] = '模式显示';


?>
