<?php
$labels['label_title'] = '電郵標簽';
$labels['label_create'] = '製作標簽';
$labels['label_set'] = '設標簽';
$labels['label_matches'] = '含有';
$labels['label_color'] = '顔色';
$labels['label_delete'] = '刪除';
$labels['label_name'] = '標簽名稱';
$labels['label_folder'] = '搜查。。';
$labels['label_all'] = '全部郵箱';
$labels['label_pref'] = '標簽管理';

$labels['deleteconfirm'] = '你是否要刪除此標簽？';
$labels['add_row'] = '加入';
$labels['delete_row'] = '删除';

$labels['headererror'] = '信息的規矩有錯誤';
$labels['inputempty'] = '含有欄不能留空白，必須填上匹配字眼';
$labels['invalidcolor'] = '顔色不正確';

$labels['check_highlighting'] = '檢查提示區模式';
$labels['highlighting'] = '提示區模式';

$labels['check_labels'] = '檢查標簽模式';
$labels['labels'] = '標簽模式';

$labels['check_error'] = '查錯模式';

$labels['label_mode'] = '模式顯示';


?>
